---
- name: setup raspberry pi as DNS server
  hosts: all
  become: yes
  tasks:
    - name: install dnscrypt-proxy
      apk:
        name: dnscrypt-proxy
        state: present
      tags:
        - configure
    - name: configure dnscrypt-proxy
      template:
        src: dnscrypt-proxy.toml.j2
        dest: /etc/dnscrypt-proxy/dnscrypt-proxy.toml
        owner: dnscrypt
        group: dnscrypt
        mode: 0400
      tags:
        - configure
    - name: provision blocked-ips.txt
      template:
        src: blocked-ips.txt.j2
        dest: /etc/dnscrypt-proxy/blocked-ips.txt
        owner: dnscrypt
        group: dnscrypt
        mode: 0400
      tags:
        - blocked-ips
    - name: set permissions to /etc/dnscrypt-proxy
      file:
        path: /etc/dnscrypt-proxy
        state: directory
        owner: dnscrypt
        group: dnscrypt
        mode: 0500
      tags:
        - configure
    - name: set permissions to /etc/dnscrypt-proxy/blocked-names.txt
      file:
        path: /etc/dnscrypt-proxy/blocked-names.txt
        state: file
        owner: dnscrypt
        group: dnscrypt
        mode: 0400
      tags:
        - configure
    - name: prepare directory for blocklist generator and its config
      file:
        path: /etc/dnscrypt-proxy/block-names-generator
        state: directory
        owner: dnscrypt
        group: dnscrypt
        mode: 0500
      tags:
        - configure
    - name: download blocklist generator
      get_url:
        url: https://github.com/DNSCrypt/dnscrypt-proxy/raw/master/utils/generate-domains-blocklist/generate-domains-blocklist.py
        dest: /etc/dnscrypt-proxy/block-names-generator/generate-domains-blocklist.py
        owner: dnscrypt
        group: dnscrypt
        mode: 0400
      tags:
        - blocked-names
    - name: provision domains-blocklist.conf
      template:
        src: domains-blocklist.conf.j2
        dest: /etc/dnscrypt-proxy/block-names-generator/domains-blocklist.conf
        owner: dnscrypt
        group: dnscrypt
        mode: 0400
      tags:
        - blocked-names
    - name: provision templates/domains-blocklist-local-additions.txt
      template:
        src: domains-blocklist-local-additions.txt.j2
        dest: /etc/dnscrypt-proxy/block-names-generator/domains-blocklist-local-additions.txt
        owner: dnscrypt
        group: dnscrypt
        mode: 0400
      tags:
        - blocked-names
    - name: provision domains-allowlist.txt from github
      get_url:
        url: https://github.com/DNSCrypt/dnscrypt-proxy/raw/master/utils/generate-domains-blocklist/domains-allowlist.txt
        dest: /etc/dnscrypt-proxy/block-names-generator/domains-allowlist.txt
        owner: dnscrypt
        group: dnscrypt
        mode: 0400
      tags:
        - blocked-names
    - name: create empty domains-time-restricted.txt
      file:
        dest: /etc/dnscrypt-proxy/block-names-generator/domains-time-restricted.txt
        state: touch
        owner: dnscrypt
        group: dnscrypt
        mode: 0400
      tags:
        - blocked-names
    - name: provision cron script
      template:
        src: cron.j2
        dest: /etc/periodic/hourly/block-names-generator
        owner: root
        group: root
        mode: 0500
      tags:
        - cron

