---
- name: prepare directory for blocklist generator and its config
  file:
    path: "{{ blocked_names_generator_path }}"
    state: directory
    owner: dnscrypt
    group: dnscrypt
    mode: 0500
  tags:
    - blocked-names

- name: download blocklist generator
  get_url:
    url: https://github.com/DNSCrypt/dnscrypt-proxy/raw/master/utils/generate-domains-blocklist/generate-domains-blocklist.py
    dest: "{{ blocked_names_generator_path }}/generate-domains-blocklist.py"
    owner: dnscrypt
    group: dnscrypt
    mode: 0400
  notify:
    - generate blocked names
  tags:
    - blocked-names

- name: provision domains-blocklist.conf
  template:
    src: domains-blocklist.conf.j2
    dest: "{{ blocked_names_generator_path }}/domains-blocklist.conf"
    owner: dnscrypt
    group: dnscrypt
    mode: 0400
  notify:
    - generate blocked names
  tags:
    - blocked-names

- name: provision domains-blocklist-local-additions.txt
  template:
    src: domains-blocklist-local-additions.txt.j2
    dest: "{{ blocked_names_generator_path }}/domains-blocklist-local-additions.txt"
    owner: dnscrypt
    group: dnscrypt
    mode: 0400
  notify:
    - generate blocked names
  tags:
    - blocked-names

- name: provision domains-allowlist.txt from github
  get_url:
    url: https://github.com/DNSCrypt/dnscrypt-proxy/raw/master/utils/generate-domains-blocklist/domains-allowlist.txt
    dest: "{{ blocked_names_generator_path }}/domains-allowlist.txt"
    owner: dnscrypt
    group: dnscrypt
    mode: 0400
  notify:
    - generate blocked names
  tags:
    - blocked-names

- name: create empty domains-time-restricted.txt
  file:
    dest: "{{ blocked_names_generator_path }}/domains-time-restricted.txt"
    state: touch
    owner: dnscrypt
    group: dnscrypt
    mode: 0400
  notify:
    - generate blocked names
  tags:
    - blocked-names

- name: prepare /usr/local/sbin directory
  file:
    path: /usr/local/sbin
    state: directory
    owner: root
    group: root
    mode: 0700
  notify:
    - generate blocked names
  tags:
    - blocked-names

- name: provision helper script
  template:
    src: blocked-names-generator.sh.j2
    dest: "{{ blocked_names_generator_helper_path }}"
    owner: root
    group: root
    mode: 0500
  notify:
    - generate blocked names
  tags:
    - blocked-names

- name: provision cron script
  template:
    src: cron.j2
    dest: /etc/periodic/hourly/blocked-names-generator
    owner: root
    group: root
    mode: 0500
  tags:
    - blocked-names
